#---------------------------------
# Repository (GitHub)
#---------------------------------

# Set clone depth to speed up clone
clone_depth: 10
# Folder to clone the repository to
clone_folder: C:\_git\Extend

# Skipping commits with noCI in commit message
skip_commits:
  message: \bnoCI\b

#---------------------------------
# Before build
#---------------------------------

# Version format
# version: '{build}'
version: 1.2.0.{build}

# Set the build worker image
image: Visual Studio 2017
build:
  verbosity: minimal

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

# Patch assembly info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Cache configuration
#cache:
#  # Cache NuGet packages until packages.config changes
#  - .Src\packages -> **\packages.config

#---------------------------------
# Build configuration
#---------------------------------

# Build OS
os: Visual Studio 2015

# Build configuration
configuration: Release

# Build platform
# platform: Any CPU

# Environment variables
environment:
  email:
    secure: 3Lt1B4c7ElWBAbKecevrRmP55DyufIcsLdVip6s+ua8=
  coverity_token:
    secure: ZI0+3VGXlTZ6NNQkmviypnUk+LJvZY4W/St9zOVZzjg=

#---------------------------------
# Build
#---------------------------------

# Script to build all the solution
build_script:
- ps: .Build\Build.ps1

#---------------------------------
# Testing
#---------------------------------

# Disable tests (Test are getting started by the build script)
test: off

#---------------------------------
# After build
#---------------------------------

# Define artifacts
artifacts:
  - path: Output
  - path: 'Output\**\*.nupkg'
    name: NuGetPackage.nupkg

# Deploy to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: EuMTEOZnx2khhY8a77sGO/tC4STC3rZe2eABB2Bq33dXoIHnATxMnMnMoOohn7eQ
#  artifact: /.*\.nupkg/
#  on:
#    # Only publish from the master branch
#    branch: master
#    # Only publish if the trigger was a Git tag
#    # git tag v0.1.0-beta
#    # git push origin --tags
#    appveyor_repo_tag: true