#---------------------------------
# Repository (GitHub)
#---------------------------------

# Set clone depth to speed up clone
clone_depth: 10
# Folder to clone the repository to
clone_folder: C:\_git\Extend

#---------------------------------
# Before build
#---------------------------------

# Version format
version: 1.1.4.{build}

# Patch assembly info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Cache configuration
cache:
  # Cache NuGet packages until packages.config changes
  - packages -> **\packages.config

#---------------------------------
# Build configuration
#---------------------------------

# Build OS
os: Windows Server 2012 R2

# Build configuration
configuration: Release

# Build platform
platform: Any CPU

#---------------------------------
# Build
#---------------------------------

# Script to build all the solution
build_script:
- ps: .Build\RunBuild.ps1

#---------------------------------
# Testing
#---------------------------------

test:
  # Assemblies to test
  assemblies:
  - .Src\Extend.Testing\bin\$(configuration)\Net40\Extend.Testing.dll
  - .Src\Extend.Testing\bin\$(configuration)\Portable\Extend.Testing.dll

#---------------------------------
# After build
#---------------------------------

# Define artifacts
artifacts:
  - path: Output
#    name: PortableExtensions.dll
#  - path: PortableExtensions\bin\Release\PortableExtensions.XML
#    name: PortableExtensions.XML
#  - path: 'NuGet\*.nupkg'
#    name: NuGetPackage.nupkg

# After Build scripts
#after_build:
#  # Create new NuGet package
#  - ps: .\NuGet\pack.ps1

# Deploy to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: EuMTEOZnx2khhY8a77sGO/tC4STC3rZe2eABB2Bq33dXoIHnATxMnMnMoOohn7eQ
#  artifact: /.*\.nupkg/